### ISSUE TITLE
This Application Needs New Data Added to "WSA Mineral Land Assessment" layer

### ISSUE THREAD

**Issue by arupke** [UGS-GIO/Minerals-Metals#16]
### Name of Existing Layer (as it appears in the application)

WSA Mineral Land Assessment

### Folder path of data

M:\Shared drives\UGS_Shared\Rupke\BLM_MLA

### Why do you feel this application needs what you're requesting?

As part of grant **UBL1**, we have scanned the remaining available WSA mineral land assessments (MLA) and they are ready to be added to the Utah mineral resource web map. A new geodatabase with all the WSA MLA locations is in the above folder path (MLA_data.gdb) and all the scanned MLA pdfs are there too (final_MLAs_all). This includes all new and previously uploaded files.

This should be the last update to this layer... unless some new MLAs are discovered, which is possible.

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

I don't know if this needs to be reviewed? @CyndiAndersen. The structure of the database is the same--only some new points have been added.

### Who has reviewed your science and grammar so far?

N/A - there is no text to review. These are scans of old US Bureau of Mines documents.

**Comment by marthajensen** [comment]
@arupke thank you! I'll add the new WSA's soon

**Comment by arupke** [comment]
Super! Thanks @marthajensen !

**Comment by marthajensen** [comment]
@arupke 

I just about have this data ready for the web. However, I have a couple of questions.

First, I am curious about two of the data points. All of the original points line up perfectly with the new data, except it appears that the data point for 1. Wahweap, Cockscomb and 2. Fish Creek, Mule Creek, Road Canyon have moved. The second point (fish creek, mule...etc) makes sense because it looks like you are now providing a separate point for Road Canyon (thus breaking it out from the original dataset with 3 areas). Was the point for Wahweap, Cockscomb moved on purpose?

I also noticed the WSA name is now different for 1. (Wahweap, Cockscomb). In the past data, we called it Wahweap, Cockscomb, in the new data it is only labeled as WSA - Wahwap. There may be other points with new WSA names as well. I am assuming you want me to overwrite the WSA name with the new ones, correct?

**Comment by marthajensen** [comment]
@arupke you got it! Thanks!

**Comment by marthajensen** [comment]
@arupke 

new data is live :) - let me know if you see any issues with it

**Comment by arupke** [comment]
@marthajensen 

Thanks, Martha! Looks great!
