### ISSUE TITLE
Add Critical Minerals Layer from C-129 as New Layer

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/Minerals-Metals#8]
**This task is not grant-funded, but still would add value to the application**

**Why do you feel this application needs what you're requesting?**
I think this set of data fits well with this application and would add a lot of value to the data so that it's accessible in an interactive map in addition to the paper publication.

**More discussion needs to be had about this feature request and how/when to implement it, but I wanted to document it here as a start. Also, I believe Rosemary has the GIS for this**

**Comment by StephMills** [comment]
@marshallrobinson  I'm in the field Mon-Wed next week, but let's catch up about this on thurs if you have time? I can set up a chat, let me know when would be good.

**Comment by marshallrobinson** [comment]
@StephMills, Thursday works fine for me. 
@marthajensen, @jjhi11, does Thursday work for you guys to talk about this app?

**Comment by marthajensen** [comment]
@StephMills @marshallrobinson I can meet on Thursday pretty much anytime - except for between 2 and 3 pm.

**Comment by jjhi11** [comment]
@StephMills works for me

**Comment by StephMills** [comment]
Ok I've got this data compiled. the gdb is in the following location:

M:\Shared drives\UGS_Energy Mineral\Webmap_MinResc

But I can move it if there are access issues. There are 3 feature classes. The main points, eg those from the critical mineral summary map in our pub, are the MainPoints. Then there is another feature for minor sites that were the black dots on our individual commodity maps. I had to do helium separately so that is the third feature class - the attribute table for helium points is totally different so I didn't combine it with the other points.

What we did in the pub is size them by importance. In the MainPoints feature class, producer>established>potential. The mill is an "FYI" point that can be discarded if you think it's too confusing. The OtherPoints are another step down (producer>established>potential>otherpoints). I think in the pub we called them "other past producers or deposits". If you want to try attributing them by commodity you're welcome to try, but I found there were too many to come up with a color or shape (or even size) scheme that differentiated well enough. I think it would be good to make the data searchable by commodity - though as I think about it I don't think I structured the OtherPoints with a single field one could search. I can add that if need be though, just let me know.

**Comment by StephMills** [comment]
I had a look at my FY21 NGGDPP grant, and because these layers contain U and V information (I said I'd update our webmaps/UMOS/mining districts for UV) I think we can use some UGP2 time on this. @arupke does that sound ok to you?

**Comment by StephMills** [comment]
As above, this one can go to UGP2

**Comment by marthajensen** [comment]
@jjhi11 The critical minerals are bundled in the app feature service - they are layer id's 13, 14, and 15
https://services.arcgis.com/ZzrwjTRez6FJiOq4/arcgis/rest/services/Metal_Mineral_Resources_web_View/FeatureServer

**Comment by jjhi11** [comment]
@arupke @StephMills 

Could please outline which fields to use for the popup and how to format the values.

**Comment by marthajensen** [comment]
I created a google sheet for the popup info - If it needs to be reformatted (fields added/removed etc) feel free. https://docs.google.com/spreadsheets/d/189h6n02j71wFa2sF5DLwdhhWT6rtwBCZH76rQrNWVPA/edit#gid=0
I will add all of the feature classes that are currently in the app to this sheet soon so we have it all in one place

**Comment by arupke** [comment]
This issue should be put on hold for now. We are applying for grant funding for next year to address this task.

**Comment by marshallrobinson** [comment]
Thanks for the heads up @arupke. Will do.

**Comment by StephMills** [comment]
[EMRI_FocusAreas_P4_UtahUpdates_Final.gdb.zip](https://github.com/UGS-GIO/Minerals-Metals/files/8027134/EMRI_FocusAreas_P4_UtahUpdates_Final.gdb.zip)

**Comment by StephMills** [comment]
Ok, getting back on this horse! This post is pertaining to metals, I'm going to have to address IMs and helium separately. 

@marthajensen I've included a spreadsheet here because I think it will be easier for you to decide how you want to setup the GIS. UTM coords in columns D and E, they're NAD83 Z12. Looks like I assigned a value in column F (Stage) that tries to summarize the level of sureness/importance of a deposit. Those levels are, in order of increasing importance:

Other deposit or occurrence < Potential resource/Other past producer < Established resource/Significant past producer < Active producer

In column H (CriticalMinerals) I've assigned a commodity for each point. The indication of major, minor, etc are not important and can be stripped off. A lot of these points have multiple critical minerals, I am not sure how I handled that - either the point is in there multiple times or I only listed the main commodity. Either is fine right now, we'll just need to think about how to deal with that for next FY. 

The most intuitive way I can think to do it is have the size attribute for Stage and color attribute for CriticalMinerals. But honestly I am not fussed so whatever you reckon!
[CriticalMinerals_MetalCommodities_10Feb2022.xls](https://github.com/UGS-GIO/Minerals-Metals/files/8043599/CriticalMinerals_MetalCommodities_10Feb2022.xls)

**Comment by StephMills** [comment]
So helium - neither Andrew nor I have worked with this data much, we got it from a guy at SITLA. But I think for current purposes it can be displayed like the metal points above with the Stage as "Other deposit or occurrence" and the CriticalMinerals as helium.
[CriticalMinerals_Helium_10Feb2022.xls](https://github.com/UGS-GIO/Minerals-Metals/files/8043617/CriticalMinerals_Helium_10Feb2022.xls)

**Comment by StephMills** [comment]
Lastly IMs, @arupke might need to double check this is the right data. I'm including a gdb that has additional commodities as points. To be honest there is probably redundancy with some of the other GIS, but I'm unsure as it has been a while since we did this. I think that if the point comes from one of the feature classes that has "producer" in the name it will be the equivalent of "Active producer", and anything else can just be considered "Other deposit or occurrence". Andrew has feature classes for dolomite, magnesium, and helium fields as polygons, I don't know how you want to handle these but they would be the equivalent of "Other deposit or occurrence". Maybe just have a look and see what you think? We are obviously happy to answer questions to help untangle this web!
[CritMins_IMs_Data.gdb.zip](https://github.com/UGS-GIO/Minerals-Metals/files/8043667/CritMins_IMs_Data.gdb.zip)

**Comment by StephMills** [comment]
and @arupke i didn't include potash anywhere, like we talked about. Assuming you'll add that whenever you're ready.

**Comment by StephMills** [comment]
And all this can be billed to UGP3!

**Comment by arupke** [comment]
@marthajensen , @StephMills ,
Here are some notes on naming the helium and IM layers for display... Let me know if you differ in opinion, Stephanie. When I refer to the IM database below, I'm referring to the CritMins_IMs_data.gdb.zip file that Stephanie added above.

As far as what attributes to show in a popup... The polygons are not attributed so we can skip that. The point features (with the exception of helium) could show SITE_NAME, PRODUCTION, and DEP_SIZE. The helium points could show _Well_Name_.

Helium-
I think we should name these features like we did in the pub:
point features named as "oil and gas well with significant helium show"
polygon features (in IM geodatabase as "helium fields") as "oil and gas field with significant helium shows"

Magnesium-
polygon features (in IM geodatabase as "magnesium") as "magnesium potential in brine"
(Stephanie, I think we skip the dolomite feature since we already have that as a IM layer)

Potash-
You can skip this. This is in review to be added as an IM layer.

Aluminum-
point features (in IM geodatabase as "alunite") as "alunite mine, prospect, or occurrence"

Fluorspar-
point features (in IM geodatabase as "fluorite") as "fluorite mine, prospect, or occurrence"

Lithium-
polygon features (in IM geodatabase as "magnesium" - the magnesium and lithium polys are the same) as "lithium potential in brine"

Barite-
point features (in IM geodatabase as "barite") as "barite mine, prospect, or occurrence"

Titanium and Zirconium-
point features (in IM geodatabase as "titanium_zirconium") as "titanium and/or zirconium prospect or occurrence"

You can ignore the kaolinite, fluorite_producers, and magnesium_producers layers at this point. Okay... that seems like a lot. Let me know if you have questions.

**Comment by marthajensen** [comment]
HI Stephanie and Andrew - after looking through these data layers, I think the easiest approach might be for me to combine all of this data into one point layer and one polygon layer for symbolization and ease of data access in the web app. So the spreadsheet you gave me (Stephanie) would be turned into points then combined with the helium data and the GIS point layers from the geodatabase.  I would add the Stage to the data that needs it.  Would that be OK? I would drop most of the fields except for the popup and symbolization fields. I could even add a field that describes whether the data is a metal, IM or helium. 

However I have some questions:

1. Can the data be combined? Or do the metals, helium and IM layers need different groupings in the web app legend?  Could all three point layers be combined into one feature class called "Critical Minerals"? If they can be combined, I'm not sure what we would name the point layer vs polygon layer. If they can't be combined, do you want three separate groups under a Critical Minerals heading (like the Industrial Minerals are now)?  


3. For symbolization, I am considering doing something similar to UMOS, but (like Stephanie suggested) with the size attribute for Stage and color attribute for CriticalMinerals.   What do you think?  The UMOS legend is below 

![image](https://user-images.githubusercontent.com/11522897/156038304-b7c22434-d18e-49ba-88a0-21bdef1902d9.png)


Let me know what you think. If it's easier to talk about this in person, lets schedule a meeting.

**Comment by StephMills** [comment]
Hi @marthajensen , I think combining everything is definitely the way to go, and no worries about dropping most of the metadata. I don't think Andrew will have any issue with that either. That attributing sounds just find to me. Just so you know, we are on the hook to do an update of the critical mineral report because the list has changed, but that won't be til next FY. But I think when we do that let's plan to work together from the outset on how to structure the GIS with some consistent metadata. Also we'll want to keep in mind versioning etc with updates, I don't want to lose this original data but not sure if we want it to be displayed on the webmap, maybe we can have a link to download older versions? Something to think about but not an issue right now. 

And SUPER SORRY for the delay on answering!!

**Comment by marthajensen** [comment]
@jjhi11 Two new Critical Mineral layers need to be added to the web application -- Critical Minerals (a point layer) and Critical Mineral Areas (a polygon layer)

Critical Minerals (point layer) (Layer ID 18)- The Critical Minerals are symbolized similar to the UMOS layer. The field CriticalMineral is being used to show the point color, while the field Stage_Value_Symbol is being used for the size of the point. The values for the Stage_Value_Symbol field and other schema information for this layer is at: https://docs.google.com/spreadsheets/d/1mJIx_yclLwMlTqrzM53cfnFXS2OCZylKVCjAWy5VvC0/edit#gid=682930863
Web popup information for this layer is at (rows 12, 13): https://docs.google.com/spreadsheets/d/1aYDaH9TQ3r7e_d46qhRwcOL0ljJx8xdtRN1vr7vqZfg/edit#gid=0

Critical Mineral Areas (polygon layer) (Layer ID 14) - this layer is symbolized on the CriticalMineral field. A popup is not needed for this layer

URL: https://services.arcgis.com/ZzrwjTRez6FJiOq4/arcgis/rest/services/Metal_Mineral_Resources_web_View/FeatureServer

**Comment by StephMills** [comment]
@jjhi11 and @marthajensen the new layers look great, I am really excited!!

Can I make two small requests? In the legend it has "Critical Mineral Areas" and "Critical Minerals", can we change that second header to be "Critical Mineral Occurrences" to emphasize the difference between polygon and point data? 

And can we make these datasets available for download in the "About" section, the way we do with the mining districts? We can provide a link to download the data as a single gdb with both the areas and occurrences, and a publication link to the critical mineral report (https://ugspub.nr.utah.gov/publications/circular/c-129.pdf). Pretty much exactly how the mining district data is available. The text can be "Locations in Utah with critical mineral potential and of known critical mineral occurrences. Definition of "critical mineral" is based on the 2018 list published by the U.S. Geological Survey. (https://www.federalregister.gov/documents/2018/05/18/2018-10667/final-list-of-critical-minerals-2018)" Ideally that web address could just be a text link (eg clicking on "2018 list" takes you to the site), if we can't embed a text link I'll come up with the formal citation instead of a web address. 

I hope that makes sense, let me know if you have any questions, thank you so much!!

**Comment by StephMills** [comment]
Sorry, quick edit on the text, we don't need critical minerals in quotes, see below:

"Locations in Utah with critical mineral potential and of known critical mineral occurrences. Definition of critical mineral is based on the 2018 list published by the U.S. Geological Survey. (https://www.federalregister.gov/documents/2018/05/18/2018-10667/final-list-of-critical-minerals-2018)"

**Comment by marthajensen** [comment]
@StephMills  
Attached is the database that matches the critical minerals information on the web. Inside the zipped folder, there is also a small schema document for the points layer. The polygon layer doesn't have a schema doc since there is only one field -- the critical mineral name field. Please let me know if you have any questions and if it's OK to make this geodatabase and schema available for download. 

[Utah_CriticalMinerals.gdb.zip](https://github.com/UGS-GIO/Minerals-Metals/files/8711552/Utah_CriticalMinerals.gdb.zip)

**Comment by StephMills** [comment]
@marthajensen yes that looks fine. Please go ahead with using that as the data available for download. Thanks!

**Comment by marthajensen** [comment]
@jjhi11 

A data download for the critical minerals data is at:
\\geology.utah.gov\www\html\apps\blm_mineral\appfiles\Utah_CriticalMinerals.gdb.zip
